postgres:
  image: postgres:9
  env_file: .env
  expose:
    - "5432"
  volumes:
    - /var/lib/postgresql
  restart: always

redis:
  image: redis
  volumes:
    - /data
  expose:
    - "6379"
  restart: always

sentry:
  image: sentry
  env_file: .env
  links:
    - postgres
    - redis
  ports:
    - "9090:9000"
  restart: always

beat:
  image: sentry
  command: sentry celery beat
  env_file: .env
  links:
    - postgres
    - redis
  restart: always

worker:
  image: sentry
  command: sentry celery worker
  env_file: .env
  links:
    - postgres
    - redis
  restart: always
